### ISSUE TITLE
sketchfab site changed Again

### ISSUE THREAD

**Issue by lumekano** [reinitialized/sketchfab-scene-exporter#15]
Srry About Bump ...

script won't work in the sketchfab.com Site .

Can You Fixed the script PlZ.

**Comment by reinitialized** [comment]
Hey, give the latest commit a shot and let me know if this resolves the issue.

**Comment by yubts** [comment]
I have problem with sketchfab too. 
![violent monkey](https://cloud.githubusercontent.com/assets/11303756/6531088/ff31b8f0-c43e-11e4-984f-8eb1a4750c10.jpg)

**Comment by reinitialized** [comment]
@yubts, I have updated the script to address the ViolentMonkey warning.

**Comment by yubts** [comment]
So, You think it's a problem with my Opera browser? So, I try reinstall all stuff, and try again script later. Thanks

**Comment by reinitialized** [comment]
@yubts, I updated the script about a half-hour ago to fix the Opera issue. I have tested this update in Opera and there are no issues.

**Comment by Spike315** [comment]
Confirmed working on Chrome with no issues so far excluding the occasional rare model that doesn't download textures. They didn't work before the PBR update messed with the script so no worries there.

Thanks for swift updates & fixes.

**Comment by yubts** [comment]
All is working!!! You the best!!!

**Comment by erteclas** [comment]
not working...
