### ISSUE TITLE
Script fails currently

### ISSUE THREAD

**Issue by HMPoweredMan** [reinitialized/sketchfab-scene-exporter#17]
Love your script man. I hope you keep up the great work, but currently the script does not work.
I hope it is something that can be fixed. Hopefully sketchfab didn't change things too much where it can't be fixed.

**Comment by guzul** [comment]
It stopped working week ago when sketchfab started to support embedding to facebook :(

**Comment by luxology** [comment]
Could you fix the script ? thank you very much.

**Comment by reinitialized** [comment]
The latest version, 6aac798 should resolve this issue. If this is confirmed to be working, I will close this.

**Comment by guzul** [comment]
Works :) Thank you very much :+1:

**Comment by erteclas** [comment]
script fail...
