### ISSUE TITLE
Site changed again

### ISSUE THREAD

**Issue by reinitialized** [reinitialized/sketchfab-scene-exporter#19]
"Download script failed... try refreshing the page"

**Comment by guzul** [comment]
indeed :( Unfortunately I don't understand how it works, so I'm unable to help :(

**Comment by jorber** [comment]
Same, on firefox and chrome :(

**Comment by SpamLicker** [comment]
I love your work man, it's helping me so much!
Hope you can find a fix :)

**Comment by ptitvincent** [comment]
Yes! We all love your work :) if you fix it you'll be our god again ;)

**Comment by nurobit** [comment]
Indeed. Lead the way!

**Comment by Slozhny** [comment]
+1

**Comment by luxology** [comment]
+1

**Comment by reinitialized** [comment]
I've decided to deprecate this project since it is no longer feasible to keep it maintained. 
Thanks

**Comment by HMPoweredMan** [comment]
Thank you for all your hard work. :D

**Comment by SpamLicker** [comment]
Thanks for everything man, you're awesome :)

**Comment by Slozhny** [comment]
Thanks a lot, you are always in our hearts.

**Comment by luxology** [comment]
Thanks for everything...
